Add nodejs templates, fix oversizedCI bugs, refactored rule_code templates
Add nodejs templates, fix oversizedCI bugs, refactored rule_code templates

diff --git a/MacLinux/rules/createRule b/MacLinux/rules/createRule
--- a/MacLinux/rules/createRule
+++ b/MacLinux/rules/createRule
@@ -1,19 +1,29 @@
 #!/bin/bash 
 # ZipFile name = $RULE_NAME.zip
-if [ $# -ne 3 ]
+if [ $# -ne 4 ]
     then
-        printf $'Usage: ./createRule PROFILE RULE_NAME APPLICABLE_RESOURCE_TYPES\n'
-		printf $'Example: ./createRule myCLIprofile requiredTagsRule "AWS::EC2::Instance,AWS::EC2::VPC"\n'
-		printf $'Use "default" for PROFILE if you want to use the default profile\n'
+        printf $'Usage: ./createRule PROFILE RUNTIME RULE_NAME APPLICABLE_RESOURCE_TYPES\n'
+		printf $'Example: ./createRule myCLIprofile nodejs requiredTagsRule "AWS::EC2::Instance,AWS::EC2::VPC"\n'
         exit 1
 fi
 PROFILE=$1
-RULE_NAME=$2
-RESOURCE_TYPES=$3
+RUNTIME=$2
+RULE_NAME=$3
+RESOURCE_TYPES=$4
+if [ "$RUNTIME" = 'nodejs' ]
+    then
+        LAMBDA_RUNTIME='nodejs6.10'
+elif [ "$RUNTIME" = 'python' ]
+    then
+        LAMBDA_RUNTIME='python3.6'     
+else
+    printf 'RUNTIME parameter must be either nodejs or python' 
+    exit 1   
+fi                
 RESOURCE_TYPES=${RESOURCE_TYPES//\"/}
 RESOURCE_TYPES=${RESOURCE_TYPES//,/\",\"}
 RESOURCE_TYPES="[\"$RESOURCE_TYPES\"]"
-zip -j $RULE_NAME.zip ruleCode/* > /dev/null
+zip -j $RULE_NAME.zip ruleCode/$RUNTIME/* > /dev/null
 if aws --profile $PROFILE iam get-role --role-name config_lambda_basic_execution 2>&1 | grep -q 'Role not found'
     then
         printf "Creating IAM role config_lambda_basic_execution\n"
@@ -30,7 +40,7 @@ if aws --profile $PROFILE iam get-role --role-name config_lambda_basic_execution
 fi
 LAMBDA_ROLE_ARN=$(aws --profile $PROFILE iam get-role --role-name config_lambda_basic_execution --query Role.Arn --output text)
 printf "Creating/Updating Lambda function $RULE_NAME\n"
-aws --profile $PROFILE lambda create-function --function-name $RULE_NAME --zip-file fileb://$RULE_NAME.zip --runtime python3.6 --role $LAMBDA_ROLE_ARN --handler rule_code.lambda_handler > /dev/null 2>&1
+aws --profile $PROFILE lambda create-function --function-name $RULE_NAME --zip-file fileb://$RULE_NAME.zip --runtime $LAMBDA_RUNTIME --role $LAMBDA_ROLE_ARN --handler rule_code.lambda_handler > /dev/null
 aws --profile $PROFILE lambda update-function-code --function-name $RULE_NAME --zip-file fileb://$RULE_NAME.zip > /dev/null
 aws --profile $PROFILE lambda add-permission --function-name $RULE_NAME --statement-id 1 --principal config.amazonaws.com --action lambda:InvokeFunction > /dev/null 2>&1
 LAMBDA_ARN=$(aws --profile $PROFILE lambda get-function --function-name $RULE_NAME --query Configuration.FunctionArn --output text)
